"""Write docker-compose .env.local from the deployed app secret."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path
from subprocess import CompletedProcess

DEFAULT_LZ_DIR = Path(__file__).resolve().parent.parent / "lz"
DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "secrets" / ".env.local"

_CHAINLIT_KEYS = frozenset(
    {"CHAINLIT_AUTH_SECRET", "CHAINLIT_DEMO_PASSWORD", "CHAINLIT_DEMO_USERNAME"}
)
_CONTAINER_ENV_KEYS = (
    "MONGODB_DATABASE",
    "VOYAGE_BASE_URL",
    "LLM_PROVIDER",
    "ENABLE_LLM",
    "SKIP_INDEX_CREATION",
    "TOP_K",
)
_ENV_ORDER = (
    "MONGODB_URI",
    "VOYAGE_API_KEY",
    "MONGODB_DATABASE",
    "VOYAGE_BASE_URL",
    "LLM_PROVIDER",
    "ENABLE_LLM",
    "SKIP_INDEX_CREATION",
    "TOP_K",
)

Run = Callable[..., CompletedProcess[str]]


class DumpLocalEnvError(RuntimeError):
    def __init__(self, message: str, *, exit_code: int = 1) -> None:
        super().__init__(message)
        self.exit_code = exit_code


def local_env_from_secret(
    secret: dict[str, object],
    *,
    mongodb_uri: str | None,
) -> tuple[dict[str, str], list[str]]:
    warnings: list[str] = []
    env: dict[str, str] = {}
    container = secret.get("container")
    if not isinstance(container, dict):
        container = {}
    container_env = container.get("env")
    if not isinstance(container_env, dict):
        container_env = {}
    secret_keys = container.get("secret_keys")
    if not isinstance(secret_keys, list):
        secret_keys = []

    if mongodb_uri:
        env["MONGODB_URI"] = mongodb_uri
    else:
        warnings.append(
            "MONGODB_URI omitted: set public_debug_access in lz/terraform.tfvars, "
            "re-apply lz, then re-run just dump-local-env."
        )

    for key in _CONTAINER_ENV_KEYS:
        if key in container_env:
            env[key] = str(container_env[key])

    for key in secret_keys:
        if not isinstance(key, str) or key in _CHAINLIT_KEYS or key in env:
            continue
        value = secret.get(key)
        if value is not None:
            env[key] = str(value)

    return env, warnings


def render_env_file(env: dict[str, str], *, secret_name: str) -> str:
    ordered = [key for key in _ENV_ORDER if key in env]
    ordered.extend(sorted(key for key in env if key not in _ENV_ORDER))
    lines = [
        "# Generated by: just dump-local-env",
        f"# Source secret: {secret_name}",
        "",
    ]
    lines.extend(f"{key}={_quote_env_value(env[key])}" for key in ordered)
    return "\n".join(lines) + "\n"


def dump_local_env(
    *,
    lz_dir: Path,
    output: Path,
    region: str | None = None,
    secret_name: str | None = None,
    mongodb_uri: str | None = None,
    run: Run = subprocess.run,
) -> Path:
    resolved_secret_name = secret_name or _terraform_raw(lz_dir, "app_secret_name", run=run)
    if not resolved_secret_name:
        raise DumpLocalEnvError("apply lz first (missing app_secret_name output)")

    resolved_region = region
    secret = _fetch_secret_json(resolved_secret_name, resolved_region or "us-east-1", run=run)
    if not resolved_region:
        aws_region = secret.get("aws_region")
        resolved_region = str(aws_region) if aws_region else "us-east-1"

    public_uri = mongodb_uri or _terraform_raw(lz_dir, "connection_string_public", run=run)
    env, warnings = local_env_from_secret(secret, mongodb_uri=public_uri)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)

    content = render_env_file(env, secret_name=resolved_secret_name)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content)
    return output


def _quote_env_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def _terraform_raw(lz_dir: Path, name: str, *, run: Run) -> str | None:
    try:
        completed = run(
            ["terraform", f"-chdir={lz_dir}", "output", "-raw", name],
            check=True,
            capture_output=True,
            text=True,
        )
    except OSError, subprocess.CalledProcessError:
        return None
    value = completed.stdout.strip()
    if not value or value == "null":
        return None
    return value


def _fetch_secret_json(secret_name: str, region: str, *, run: Run) -> dict[str, object]:
    try:
        completed = run(
            [
                "aws",
                "secretsmanager",
                "get-secret-value",
                "--secret-id",
                secret_name,
                "--region",
                region,
                "--query",
                "SecretString",
                "--output",
                "text",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise DumpLocalEnvError(f"could not read secret {secret_name!r} in {region}") from exc
    return json.loads(completed.stdout)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Dump local Docker env from the app secret.")
    parser.add_argument("--lz-dir", type=Path, default=DEFAULT_LZ_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--region")
    parser.add_argument("--secret-name")
    parser.add_argument("--mongodb-uri")
    args = parser.parse_args(argv)
    try:
        path = dump_local_env(
            lz_dir=args.lz_dir,
            output=args.output,
            region=args.region,
            secret_name=args.secret_name,
            mongodb_uri=args.mongodb_uri,
        )
    except DumpLocalEnvError as exc:
        print(exc, file=sys.stderr)
        return exc.exit_code
    print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
